# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='content_textcontent', serialize=False, to='cms.CMSPlugin')),
                ('css_class', models.CharField(blank=True, max_length=64, verbose_name='CSS Class')),
                ('headline', models.CharField(blank=True, max_length=255, verbose_name='Headline')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin', models.Model),
        ),
    ]
