# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 18:31
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlainTextContent',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='content_plaintextcontent', serialize=False, to='cms.CMSPlugin')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('html', models.BooleanField(default=False, verbose_name='Allow HTML')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TeaserContent',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='content_teasercontent', serialize=False, to='cms.CMSPlugin')),
                ('teaser', models.TextField(blank=True, verbose_name='Teaser')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='content_textcontent', serialize=False, to='cms.CMSPlugin')),
                ('headline', models.CharField(blank=True, max_length=4000, verbose_name='Headline')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('link', models.CharField(blank=True, max_length=4000, verbose_name='Link')),
                ('link_text', models.CharField(blank=True, max_length=4000, verbose_name='Link Text')),
                ('alignment', models.CharField(choices=[(b'top', 'Top'), (b'left', 'Left')], default=b'top', max_length=10, verbose_name='Title Alignment')),
                ('theme', models.CharField(choices=[(b'page-title', 'Page Title'), (b'regular', 'Regular (White)'), (b'secondary', 'Secondary (Grey)')], default=b'regular', max_length=10, verbose_name='Background Theme')),
                ('page', cms.models.fields.PageField(blank=True, help_text='If both link and cms page is defined, the link is preferred.', null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page', verbose_name=b'CMS Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
