# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 16:38
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcontent',
            name='alignment',
            field=models.CharField(choices=[('top', 'Top'), ('left', 'Left')], default='top', max_length=10, verbose_name='Title Alignment'),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='page',
            field=cms.models.fields.PageField(blank=True, help_text='If both link and cms page is defined, the link is preferred.', null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page', verbose_name='CMS Page'),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='theme',
            field=models.CharField(choices=[('page-title', 'Page Title'), ('regular', 'Regular (White)'), ('secondary', 'Secondary (Grey)')], default='regular', max_length=10, verbose_name='Background Theme'),
        ),
    ]
