# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textcontent',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='TextContent',
        ),
    ]
