# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 16:26
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('content', '0003_teasercontent_textcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='textcontent',
            name='link_text',
            field=models.CharField(blank=True, max_length=4000, verbose_name='Link Text'),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='page',
            field=cms.models.fields.PageField(blank=True, help_text='If both link and cms page is defined, the link is preferred.', null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page', verbose_name=b'CMS Page'),
        ),
        migrations.AlterField(
            model_name='teasercontent',
            name='teaser',
            field=models.TextField(blank=True, verbose_name='Teaser'),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='theme',
            field=models.CharField(choices=[(b'page-title', 'Page Title'), (b'regular', 'Regular (White)'), (b'secondary', 'Secondary (Grey)')], default=b'regular', max_length=10, verbose_name='Background Theme'),
        ),
    ]
