# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('content', '0004_auto_20180105_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlainTextContent',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='content_plaintextcontent', serialize=False, to='cms.CMSPlugin')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('html', models.BooleanField(default=False, verbose_name='Allow HTML')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
