# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 16:38
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='page',
            field=cms.models.fields.PageField(blank=True, help_text='If both link and cms page is defined, the link is preferred.', null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page', verbose_name='CMS Page'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='page',
            field=cms.models.fields.PageField(blank=True, help_text='If both link and cms page is defined, the link is preferred.', null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page', verbose_name='CMS Page'),
        ),
    ]
