# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 11:49
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djde', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='credit',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True, verbose_name='Image Credit'),
        ),
    ]
