# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 17:49
from __future__ import unicode_literals

import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='schedule_event', serialize=False, to='cms.CMSPlugin')),
                ('headline', models.CharField(blank=True, max_length=4000, verbose_name='Headline')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('date', models.DateField(blank=True, verbose_name='Date')),
                ('recurring', models.BooleanField(default=False, verbose_name='Recurring')),
                ('link', models.CharField(blank=True, max_length=4000, verbose_name='Link')),
                ('link_text', models.CharField(blank=True, max_length=4000, verbose_name='Link Text')),
                ('main_image', filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Main Image')),
                ('page', cms.models.fields.PageField(blank=True, help_text='If both link and cms page is defined, the link is preferred.', null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page', verbose_name=b'CMS Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='schedule_eventimage', serialize=False, to='cms.CMSPlugin')),
                ('image', filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='schedule_schedule', serialize=False, to='cms.CMSPlugin')),
                ('headline', models.CharField(blank=True, max_length=4000, verbose_name='Headline')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
