# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 16:38
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion
import filer.fields.folder


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventimage',
            name='cmsplugin_ptr',
        ),
        migrations.RemoveField(
            model_name='eventimage',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='gallery',
            field=filer.fields.folder.FilerFolderField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Folder', verbose_name='Image Gallery'),
        ),
        migrations.AlterField(
            model_name='event',
            name='page',
            field=cms.models.fields.PageField(blank=True, help_text='If both link and cms page is defined, the link is preferred.', null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page', verbose_name='CMS Page'),
        ),
        migrations.DeleteModel(
            name='EventImage',
        ),
    ]
