# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 17:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='main_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=filer.fields.image.FilerImageField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Image'),
            preserve_default=False,
        ),
    ]
